name: MIKEANDTANE
favicon: null
layout_spectrum: 0.15039
typography_spectrum: 0.18085
title: MIKEANDTANE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#404040'
    - '#585858'
    - '#281f18'
    - '#ad8876'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.45003327168524265
purpose: []
